/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProdReadinessRouteImport } from './routes/prod-readiness'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as MatchRouteImport } from './routes/match'
import { Route as InstitutionsRouteImport } from './routes/institutions'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as FundingRouteImport } from './routes/funding'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstitutionsSlugRouteImport } from './routes/institutions.$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as CareersSlugRouteImport } from './routes/careers.$slug'
import { Route as AdminDataRouteImport } from './routes/admin.data'
import { Route as AdminDataRouteImport } from './routes/admin.data'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdReadinessRoute = ProdReadinessRouteImport.update({
  id: '/prod-readiness',
  path: '/prod-readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsRoute = InstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const FundingRoute = FundingRouteImport.update({
  id: '/funding',
  path: '/funding',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsSlugRoute = InstitutionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InstitutionsRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const CareersSlugRoute = CareersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CareersRoute,
const AdminDataRoute = AdminDataRouteImport.update({
  id: '/admin/data',
  path: '/admin/data',
  getParentRoute: () => rootRouteImport,
} as any)
} as any)
const AdminDataRoute = AdminDataRouteImport.update({
  id: '/admin/data',
  path: '/admin/data',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/careers': typeof CareersRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/funding': typeof FundingRoute
  '/guides': typeof GuidesRouteWithChildren
  '/institutions': typeof InstitutionsRouteWithChildren
  '/admin/data': typeof AdminDataRoute
  '/match': typeof MatchRoute
  '/opportunities': typeof OpportunitiesRoute
  '/prod-readiness': typeof ProdReadinessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills': typeof SkillsRoute
  '/unlock': typeof UnlockRoute
  '/admin/data': typeof AdminDataRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/institutions/$slug': typeof InstitutionsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/careers': typeof CareersRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/funding': typeof FundingRoute
  '/guides': typeof GuidesRouteWithChildren
  '/admin/data': typeof AdminDataRoute
  '/institutions': typeof InstitutionsRouteWithChildren
  '/match': typeof MatchRoute
  '/opportunities': typeof OpportunitiesRoute
  '/prod-readiness': typeof ProdReadinessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills': typeof SkillsRoute
  '/unlock': typeof UnlockRoute
  '/admin/data': typeof AdminDataRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/institutions/$slug': typeof InstitutionsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/careers': typeof CareersRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/funding': typeof FundingRoute
  '/admin/data': typeof AdminDataRoute
  '/guides': typeof GuidesRouteWithChildren
  '/institutions': typeof InstitutionsRouteWithChildren
  '/match': typeof MatchRoute
  '/opportunities': typeof OpportunitiesRoute
  '/prod-readiness': typeof ProdReadinessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills': typeof SkillsRoute
  '/unlock': typeof UnlockRoute
  '/admin/data': typeof AdminDataRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/institutions/$slug': typeof InstitutionsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/careers'
    | '/courses'
    | '/admin/data'
    | '/funding'
    | '/guides'
    | '/institutions'
    | '/match'
    | '/opportunities'
    | '/prod-readiness'
    | '/sitemap.xml'
    | '/skills'
    | '/unlock'
    | '/admin/data'
    | '/careers/$slug'
    | '/courses/$slug'
    | '/guides/$slug'
    | '/institutions/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/careers'
    | '/admin/data'
    | '/courses'
    | '/funding'
    | '/guides'
    | '/institutions'
    | '/match'
    | '/opportunities'
    | '/prod-readiness'
    | '/sitemap.xml'
    | '/skills'
    | '/unlock'
    | '/admin/data'
    | '/careers/$slug'
    | '/courses/$slug'
    | '/guides/$slug'
    | '/institutions/$slug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin/data'
    | '/careers'
    | '/courses'
    | '/funding'
    | '/guides'
    | '/institutions'
    | '/match'
    | '/opportunities'
    | '/prod-readiness'
    | '/sitemap.xml'
    | '/skills'
    | '/unlock'
    | '/admin/data'
    | '/careers/$slug'
    | '/courses/$slug'
    | '/guides/$slug'
    | '/institutions/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDataRoute: typeof AdminDataRoute
  AccountRoute: typeof AccountRoute
  CareersRoute: typeof CareersRouteWithChildren
  CoursesRoute: typeof CoursesRouteWithChildren
  FundingRoute: typeof FundingRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  InstitutionsRoute: typeof InstitutionsRouteWithChildren
  MatchRoute: typeof MatchRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  ProdReadinessRoute: typeof ProdReadinessRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SkillsRoute: typeof SkillsRoute
  UnlockRoute: typeof UnlockRoute
  AdminDataRoute: typeof AdminDataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prod-readiness': {
      id: '/prod-readiness'
      path: '/prod-readiness'
      fullPath: '/prod-readiness'
      preLoaderRoute: typeof ProdReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions': {
      id: '/institutions'
      path: '/institutions'
      fullPath: '/institutions'
      preLoaderRoute: typeof InstitutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funding': {
      id: '/funding'
      path: '/funding'
      fullPath: '/funding'
      preLoaderRoute: typeof FundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions/$slug': {
      id: '/institutions/$slug'
      path: '/$slug'
      fullPath: '/institutions/$slug'
      preLoaderRoute: typeof InstitutionsSlugRouteImport
      parentRoute: typeof InstitutionsRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/courses/$slug': {
    '/admin/data': {
      id: '/admin/data'
      path: '/admin/data'
      fullPath: '/admin/data'
      preLoaderRoute: typeof AdminDataRouteImport
      parentRoute: typeof rootRouteImport
    }
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/careers/$slug': {
      id: '/careers/$slug'
      path: '/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof CareersSlugRouteImport
      parentRoute: typeof CareersRoute
    }
    '/admin/data': {
      id: '/admin/data'
      path: '/admin/data'
      fullPath: '/admin/data'
      preLoaderRoute: typeof AdminDataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CareersRouteChildren {
  CareersSlugRoute: typeof CareersSlugRoute
}

const CareersRouteChildren: CareersRouteChildren = {
  CareersSlugRoute: CareersSlugRoute,
}

const CareersRouteWithChildren =
  CareersRoute._addFileChildren(CareersRouteChildren)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

interface InstitutionsRouteChildren {
  InstitutionsSlugRoute: typeof InstitutionsSlugRoute
}

const InstitutionsRouteChildren: InstitutionsRouteChildren = {
  InstitutionsSlugRoute: InstitutionsSlugRoute,
  AdminDataRoute: AdminDataRoute,
}

const InstitutionsRouteWithChildren = InstitutionsRoute._addFileChildren(
  InstitutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CareersRoute: CareersRouteWithChildren,
  CoursesRoute: CoursesRouteWithChildren,
  FundingRoute: FundingRoute,
  GuidesRoute: GuidesRouteWithChildren,
  InstitutionsRoute: InstitutionsRouteWithChildren,
  MatchRoute: MatchRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  ProdReadinessRoute: ProdReadinessRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SkillsRoute: SkillsRoute,
  UnlockRoute: UnlockRoute,
  AdminDataRoute: AdminDataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
